package:
  name: perl-sereal-decoder
  version: "4.021"

source:
  url: https://cpan.metacpan.org/authors/id/Y/YV/YVES/Sereal-Decoder-4.021.tar.gz
  sha256: b4ee837b0500430afeb620057f325a3bbfade6b6b1fc097bd83c63ba75fc4210

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    
  host:
    - perl
    - perl-file-path
    - perl-test-warn
    - perl-test-simple
    - perl-extutils-makemaker
    - perl-test-longstring
    - perl-scalar-list-utils
    - perl-pathtools
    - perl-extutils-parsexs

  run:
    - perl

test:
  imports:
    - Sereal::Decoder
    - Sereal::Decoder::Constants
    - Sereal::Performance

about:
  home: http://metacpan.org/pod/Sereal::Decoder
  license: perl_5
  summary: 'Fast, compact, powerful binary deserialization'

